---
fit:
  data:
    class_path: MVSLocalDataModule
    init_args:
      bf: &bf 96
      dist_list: &dist_list [0.5, 1, 2, 5, 7.5, 10, 15, 20, 50, 100]
      data_dirs: &data_names
        main: # Code always expects "main" dataset
          path: "/dataset/"
          specified_csv: null
          print_imgs: False
          compute_metrics: True
          batch_size: &batch_size 8
        per_env:
          path: "/dataset/"
          specified_csv: "/dataset/per_env_list.csv"
          print_imgs: True
          compute_metrics: False
          batch_size: 1
      shuffle_train: True
      shuffle_val: False
      num_workers: 16

  model:
    class_path: dsta_mvs.model.mvs_model.spherical_sweep_stereo.SphericalSweepStereo
    init_args:
      
      val_loader_names: *data_names

      feature_extractor:
        class_path: SphereEquirectFeatExtraction
        init_args:
          in_size: [512, 2048]
          in_chs: 3
          chs: &feat_chs 8
          k_sz: 3
          layers: [5, 10]
          norm_type: 'batch'
          relu_type: &relu_type 'leaky'
      
      cv_builder:
        class_path: SphericalSweepStdMasked
        init_args:
          num_cams: &num_cams 3
          feat_chs: &vol_chs 8
          post_k_sz: 3
          norm_type: 'batch'
          relu_type: *relu_type
      
      cv_regulator:
        class_path: UNetCostVolumeRegulator
        init_args:
          in_chs: *vol_chs
          final_chs: 1
          u_depth: 2
          blk_width: 2
          stage_factor: 2
          cost_k_sz: 3
          keep_last_chs: [] # TODO: What does this do?
          deconv_k_sz: 3
          sweep_fuse_ch_reduce: 2
          num_cams: *num_cams
          only_one_cam: True
          norm_type: 'batch'
          relu_type: *relu_type
      
      dist_regressor: &dist_regressor_var
        class_path: DistanceRegressorWithFixedCandidates
        init_args:
          bf: *bf
          dist_cands: *dist_list
          interp_scale_factor: 2
          pre_interp: True
      
      augmentation: 
        class_path: dsta_mvs.support.augmentation.AugmentationSequence
        init_args:
          transforms:
            - class_path: RandomSingleImageMasking
              init_args:
                scale: [0.05, 0.20]
                ratio: [0.3, 3.3]
                value: 0.0
                same_on_batch: False
                p: 1.0
      
      validation_metrics:
        ssim:
          class_path: SSIMMetric
          init_args:
            bf: *bf
            dist_list: *dist_list
        rmse:
          class_path: RMSEMetric
          init_args:
            bf: *bf
            dist_list: *dist_list
        mae:
          class_path: MAEMetric
          init_args:
            bf: *bf
            dist_list: *dist_list
      
      volume_loss: 
        class_path: VolumeCrossEntropy
        init_args:
          bf: *bf
          dist_list: *dist_list
      
      distance_loss: 
        class_path: torch.nn.SmoothL1Loss
      
      loss_weights: [1.0, 0.0]      

  optimizer:
    class_path: Adam
    init_args:
      lr: 0.0001

  trainer:
    accelerator: gpu
    devices: 4
    strategy: ddp
    max_epochs: 1000
    logger:
      class_path: WandbLogger
      init_args:
        project: dsta-mvs-refactor
        name: test_multi_vals
        log_model: all
        save_dir: wandb_logs
    callbacks:
      - class_path: ModelCheckpoint
        init_args:
          save_top_k: -1    # save every model
          every_n_epochs: 1 # save every epoch
