sweep@exp_name: "dsta_sweep_config24"
#8L
sweep@dist_list: [0.5, 0.5828476269775187, 0.6986027944111776, 0.87173100871731, 1.1589403973509933, 1.728395061728395, 3.3980582524271843, 100.0]
fit.model.init_args.volume_loss: sweep_configs/vol_loss.yaml
#L1 Loss 100% Weighting
fit.model.init_args.loss_weights: [0.0, 1.0]
fit.model.init_args.augmentation.init_args: sweep_configs/no_masking.yaml
fit.model.init_args.feature_extractor: sweep_configs/simple_featext.yaml
fit.model.init_args.cv_builder: sweep_configs/concat_cvbuilder.yaml
fit.model.init_args.cv_regulator.init_args.in_chs: 48
fit.data.init_args.data_dirs.main.batch_size: 4